title: Data Analysis @BME
description: Course material for the advanced programming and data analysis course (TU/e)
theme: just-the-docs

url: ml.github.io/BME_data_analysis

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
